### ISSUE TITLE
Implement /builds as a section of the website instead of a separate app

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#142]
## Goal 
Consolidate https://github.com/ember-learn/builds into this app under the `/builds` route

### Todo

- [ ] Add what is currently the application route of the [Builds App](https://github.com/ember-learn/builds) as the `/builds` route of the new website
- [ ] add each of the routes in the Builds App as subroutes of `build` e.g. `builds/canary`, `/builds/beta`, `/builds/release`
- [ ] add all of the added routes to the premberUrls https://github.com/ember-learn/ember-website/blob/master/ember-cli-build.js#L23

**Comment by HallDJack** [comment]
@mansona I am going to try and pick this issue up when I have some time. I want to confirm the acceptance criteria for this issue.

My understanding is that this issue will be considered resolved when the [ember-learn/builds](
https://github.com/ember-learn/builds) app has been migrated in to this application and its pages live under the `/builds` route.

Is that correct?

A few other questions to make sure I understand what needs to be done:
- Should `/builds` show what is currently shown under 'Home'?
- Should the other routes be `/builds/canary`, `/builds/beta`, `/builds/release`?
- Is it correct that no route is needed for LTS?

**Comment by locks** [comment]
Thanks for picking it up @HallDJack!
In short:
- Yes
- Yes
- No

The first phase is to port it over to be functionally the same. For the next phases we might want to propose changes through an RFC.
Oh, one little thing, instead of `/builds`, it should be `/releases`. We have already [included a redirect](https://github.com/ember-learn/ember-website/blob/master/.netlifyredirects#L5) since we decided to make that change.

**Comment by mansona** [comment]
@HallDJack you are 100% correct, this will be considered done when everything that **currently** exists in the builds app lives in this app 👍 

You are also correct that we do **not** need a route for LTS 👍 This is a follow-up issue that covers adding functionality to the builds routes but we will be starting to work on that in Phase 2, we don't want it to hold up getting this live 💪

**Comment by HallDJack** [comment]
Thanks @locks & @mansona.

I think I should have time to do some work on this over the weekend.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HallDJack** [comment]
Hey @locks or @mansona,

It looks like this repo is putting component templates in `app/components` instead of `app/templates/components`, but I still see a `app/templates/components` directory. I am going to follow the established pattern of putting component templates in `app/components`, but I wanted to confirm that was the desired pattern.

**Comment by HallDJack** [comment]
Thanks for the offer @mansona.

I have a branch with all the functionality ported over I just need to pull in the styles. I haven’t had time to work on it this week, but should have time this weekend.

If that doesn’t fit the timeframe that is needed I could PR what I have and let someone else take over. Let me know if I should do that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mansona** [comment]
@HallDJack I would always PR what you have already so people can take a look, but if you get to it this weekend that should be ok on the timeframe 🎉 also I wouldn't worry too much if you don't (in case you get busy) because any contribution is very welcome no matter how big or small!

I will say that I wouldn't worry too much about the styles for 2 reasons: firstly if you look at #154 the styles that were ported over from the statusboard app could do with some **serious** love 🙈 and secondly, we have a final stage of the process that will be making more sweeping changes https://github.com/ember-learn/ember-website/issues/157

When you're looking at this over the weekend I would recommend making it as quick a copy-paste job as you can make it 👍

**Comment by HallDJack** [comment]
@mansona I got the styles _mostly_ working. PR for the port here: https://github.com/ember-learn/ember-website/pull/159
