### ISSUE TITLE
Add times of meetings in the Team page

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-website#143]
At the moment, various core and non-core teams have recurring weekly meetings.
It is hard to keep track of this, so having this information consolidated in a single page would be a boon.

## Tasks
- [ ] Gather time, day of the week, and whether the meeting is generally open to the public or not
- [ ] List it on the teams page
- [ ] Make a nice calendar visualization

**Comment by mansona** [comment]
This is still a relevant issue 🤔

**Comment by hakilebara** [comment]
Can the calendar visualization be taken out of this issue? I think it deserves a issue of its own. It is more of a nice to have than an actual blocker.

**Comment by prasannavijayan** [comment]
@mansona Can I take a look at this one?
