### ISSUE TITLE
Clean up the CSS and templates for the releases routes

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#162]
As a result of #159 we have "copy & pasted" the styles and templates from https://github.com/ember-learn/builds into this application. The job was specifically **not** to optimise the CSS or the templates and instead to just quickly port over the functionality.

We need to go back and refactor the implementation to **simplify** as much as possible.

### Todo: 

- [ ] Significantly reduce the amount of custom CSS required to implement the functionality
- [ ] Remove any over-generalisations (e.g. using components exactly once)  
- [x] clean up the templates to make them much simpler and easier to contribute
- [ ] optionally move some of the common UI elements to the ember-styleguide (or just replace them with existing styleguide elements)

**Comment by mansona** [comment]
some of the simplification of the templates has now happened in #298 

There is a lot that can still be improved but we are making progress 🎉
