### ISSUE TITLE
Port the current year's community survey page

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#173]
This task is to port the https://emberjs.com/ember-community-survey-2019/ page from the previous website. There are some specific requirements for this implementation that make it slightly more complex than a normal static html port: 

### Todo
- [ ] port the static html for the page
- [ ] make sure that the banner introduced in #171 does **not** show on this page
- [ ] create a banner that has the countdown until the end of the survey as exists on the current live site

**Comment by patocallaghan** [comment]
✋ I'll take this one as it's related to https://github.com/ember-learn/ember-website/pull/177
