### ISSUE TITLE
[redesign] Add content for the landing page header

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#314]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

![Screenshot 2019-04-23 at 11 59 04](https://user-images.githubusercontent.com/594890/56576033-3bec1f80-65bf-11e9-8752-90a2b3ac0e78.png)

Add the content for the hero section of the homepage.

## Todo

- [x] remove the existing content that makes up the "hero" section of the website
  - `A framework for ambitious web developers. Try it out!`
- [x] use `EsPageHeader` to create the new hero section
- [x] make sure it has a dark background

## useful documentation

- https://website-redesign-rfc--ember-styleguide.netlify.com/components/page-header
- https://website-redesign-rfc--ember-styleguide.netlify.com/css/helpers#dark

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `website-redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason.

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by claeusdev** [comment]
@mansona I would like to have a go at this.

**Comment by mansona** [comment]
hey @claeusdev I have already completed this one in https://github.com/ember-learn/ember-website/pull/362 and I'm just waiting to hear back from Percy to see why CI is breaking on their side. 

If you would like to take a look at an issue it would be great if you could check out https://github.com/ember-learn/ember-website/issues/315 👍

**Comment by claeusdev** [comment]
@mansona Hey lemme check it out and then I'll ping you on discord to get started.
