### ISSUE TITLE
[redesign] Add content for the landing page main section

### ISSUE THREAD

**Issue by ghislaineguerin** [ember-learn/ember-website#315]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

![image](https://user-images.githubusercontent.com/845767/57195653-7063c200-6f55-11e9-9ee5-abc3e0460ecd.png)

Add the content for the main section of the website

## Blockers 

- [x] Create documentation for typography classes
- [x] Create documentation for grid layout classes
- [x] Create helper classes for background colours
- [ ] Create documentation for image placement classes
- [ ] Create helper classes for background image placement

## Todo

- [ ] Recreate all the content sections applying the typography and layout classes
- [ ] Replace mockup content with the actual content

## Useful Documentation

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `website-redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason.

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by mansona** [comment]
hey @ghislaineguerin I'm just wondering if you think this issue can be picked up now or should we still wait for the other ToDo items to be completed before starting?

**Comment by ghislaineguerin** [comment]
@mansona I think this can be picked and we could finalize any additional requirements based on the initial implementation.

**Comment by mansona** [comment]
@ghislaineguerin cool 🎉 thanks for replying so quickly 😂 

I'll remove you from the assignees to this task as it is more about implementation on the **website** repo than on the styleguide. Let me know if you need any help creating corresponding issues on the styleguide repo 👍

**Comment by NullVoxPopuli** [comment]
dibs!

**Comment by balinterdi** [comment]
I've just started working on this.

**Comment by mansona** [comment]
fixed in #380
