### ISSUE TITLE
[redesign] Add content for a Component Example on the hompage

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#364]
> If this is your first time tackling an issue that is part of the redesign project please read all the **Notes** section at the bottom of this issue before claiming it and starting to work on it

<img width="706" alt="Screenshot 2019-07-25 at 10 55 26" src="https://user-images.githubusercontent.com/594890/61865339-f47d7400-aeca-11e9-915b-06283ac66a23.png">

Add the content for the Component example on the homepage. You only need to add one toy example as the content of the examples is still being discussed

## Blockers (ember-styleguide)

- [ ] Create documentation for code samples
- [ ] Create component that can use Prism to highlight code

## Todo

- [ ] Use code sample component on the homepage

## useful documentation

(add when styleguide has been updated)

--- 

## Notes (important) 
This issue is part of the [Ember Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) and if you are not familiar with the RFC you should read it and look at the example landing page before attempting this issue.

When creating your PR you should target the `redesign-rfc` branch. This way when your PR is merged it will not update `master` it will instead update the long-lived branch that is tracking the website redesign work.

This issue is strictly to add **the content** for a section of the homepage. All styles should be provided by the ember-styleguide and we should not be adding styles to the ember-website for any reason. To see the documentation of the styleguide you can go to https://deploy-preview-145--ember-styleguide.netlify.com/

If you find that there is documentation or implementation lacking in the ember-styleguide to adequately tackle this issue then part of the deliverable of this issue is to document what is missing 👍 this will facilitate improvements in the ember-styleguide that will allow you to complete your work and get your PR merged.

**Comment by mansona** [comment]
This has been deferred until we have the right content to include in the examples. It is unlikely to be in the first phase of the project
