### ISSUE TITLE
Figure out why the vendor.js is so large

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#394]
http://requestmap.webperf.tools/render/190830_3B_167426830c5988080087e181e8415c1e

This needs to be fixed on master and the changes cherry-picked to the redesign branch 👍 

## To Do

- [x] dynamically load highcharts only on the survey results page https://github.com/ember-learn/ember-website/issues/395
- [x] dynamically load leaflet only on the meetups page https://github.com/ember-learn/ember-website/issues/396
- [x] optimise the size of svg-jar svgs https://github.com/ember-learn/ember-website/issues/419
- [x] remove the implementation of highlightjs and markdown-it from the releases page and do this work at build time (as we already have broccoli-static-site-json) https://github.com/ember-learn/ember-website/issues/420
- [x] remove the need for ember-moment

**Comment by NullVoxPopuli** [comment]
There are a lot of quick wins we can gain here:
![image](https://user-images.githubusercontent.com/199018/65516574-162cb480-de96-11e9-9f78-d62be8aafd2d.png)

**Comment by NullVoxPopuli** [comment]
Biggest wins, I think are:
 dynamically loading: 
   - Prism.JS (instead of highlight)
     - smaller (~90% savings (choosing what languages to support reduces this a ton)) 
     - better hbs support, etc
   - leaflet
   - highcharts

More ambitious bundle reduction:
 - ember-auto-import instead of ember-wrapper addons
 - replace momentjs with datefns or similar ( => 50% savings)
 - replace markdown-it with showdown (30% savings)
 - remove ember-svg-jar or dynamically load it, if it really is a production-time dependency

**Comment by mansona** [comment]
Hey sorry for the delay but I also did an analysis using bundle analyser a few weeks ago but didn't get a chance to post it because 👶 arrived 😂 

Here is an analysis of the findings: https://docs.google.com/spreadsheets/d/1SlvSNWRc3-s8CLCiTvlAXXOle3YUPsvLNdtCFiH_W9Y/edit?usp=sharing

## To Do

- [ ] dynamically load highcharts only on the survey results page https://github.com/ember-learn/ember-website/issues/395
- [ ] dynamically load leaflet only on the meetups page https://github.com/ember-learn/ember-website/issues/396
- [ ] optimise the size of svg-jar svgs
- [ ] remove the implementation of highlightjs and markdown-it from the releases page and do this work at build time (as we already have broccoli-static-site-json)

**Comment by mansona** [comment]
Also @NullVoxPopuli I think we **can** get away with only targeting evergreen browsers but we need to have a way to only execute JS on those browsers 🤔 because everything should be the same in prember and the links should all work we can get away with a "static only" render for legacy browsers 

I did attempt to try out the modules thing but it doesn't work with ember-cli currently 😞

**Comment by pichfl** [comment]
Something I noticed: We should remove the `ember-moment` and replace it by two smaller and smarter helpers using the JS intl API.

**Comment by mansona** [comment]
Fixed in #528
