### ISSUE TITLE
Install ember-template-lint and eslint

### ISSUE THREAD

**Issue by ef4** [ember-learn/ember-website#669]
## Background

The `ember-website` still relies on `ember-cli-template-lint` and `ember-cli-eslint`. Neither package is maintained anymore. Since Ember 3.17, the recommended path has been to use `ember-template-lint` and `eslint` instead.

## Problem

We'll reinstall lint-related packages so that the app uses the latest versions to maintain code. Doing so will result in lint failures because more rules exist in `ember-template-lint` and `eslint`.

For now, we'll enumerate the names of all lint rules that failed, then add these as exceptions in `.template-lintrc.js` and `.eslintrc.js`, respectively.

## TODOs

- [ ] Reinstall lint-related packages by running the following commands:

    ```bash
    # Uninstall packages (because npm has trouble with updating to a next major version) 
    npm uninstall ember-cli-template-lint ember-template-lint ember-cli-eslint eslint-plugin-ember eslint-plugin-node

    # Install ember-template-lint, eslint, eslint-plugin-ember, eslint-plugin-node
    npm install --save-dev ember-template-lint eslint eslint-plugin-ember eslint-plugin-node
    ```

- [ ] Run `npm run lint:hbs` to find lint errors. The name of a rule appears at the end, e.g. `no-curly-component-invocation` and `no-implicit-this`.

    ```bash
    app/templates/application.hbs
      1:0  error  You are using the component {{head-layout}} with curly component syntax. You should use <HeadLayout> instead. If it is actually a helper you must manually add it to the 'no-curly-component-invocation' rule configuration, e.g. `'no-curly-component-invocation': { allow: ['head-layout'] }`.  no-curly-component-invocation
      1:2  error  Ambiguous path 'head-layout' is not allowed. Use '@head-layout' if it is a named argument or 'this.head-layout' if it is a property on 'this'. If it is a helper or component that has no arguments, you must either convert it to an angle bracket invocation or manually add it to the 'no-implicit-this' rule configuration, e.g. 'no-implicit-this': { allow: ['head-layout'] }.  no-implicit-this
    ...
    ```

- [ ] Add the names of rules that failed to the `rules` object in the `.template-lintrc.js` file. To help track the rules, please alphabetize the names.

- [ ] (optional) To help prioritize fixing the errors, can you count how many times the app didn't meet each rule (e.g. by using Find All in your text editor)? Please add the counts to your pull request description (e.g. as a table).

- [ ] Repeat the 3 steps above for `npm run lint:js`. Add the names of rules that failed to the `rules` object (just before `overrides`) in `.eslintrc.js`. If you can also report the counts, that'd be great!

After you have added exceptions, running `npm run lint:hbs` and `npm run lint:js` should result in 0 lint errors. We'll create separate issues to fix the suppressed errors.

## Notes

After installing the latest `eslint`, running `npm run lint:js` will result in the following error:

```bash
ESLint: 7.11.0

Error: ESLint configuration of global 'L' in .eslintrc.js is invalid:
'1' is not a valid configuration for a global (use 'readonly', 'writable', or 'off')
```

This has to do with the `globals` object in `.eslintrc.js`. Based on https://github.com/eslint/eslint/pull/11517/files and possibly other resources, please find out how to update the syntax `L: 1`.

## References

<details>
<summary>Original description (no longer applicable but kept for reference)</summary>

The octane-specific hbs lint rules are enabled, but not running because ember-template-lint needs to be upgraded. You can upgrade by making these changes in package.json:

```diff
diff --git a/package.json b/package.json
index d34d107..cea08e8 100644
--- a/package.json
+++ b/package.json
@@ -46,7 +46,6 @@
     "ember-cli-netlify": "^0.3.0",
     "ember-cli-sri": "^2.1.1",
     "ember-cli-stylelint": "^3.0.1",
-    "ember-cli-template-lint": "^1.0.0-beta.3",
     "ember-cli-uglify": "^3.0.0",
     "ember-data": "~3.16.0",
     "ember-export-application-global": "^2.0.1",
@@ -63,7 +62,7 @@
     "ember-resolver": "^7.0.0",
     "ember-source": "~3.16.0",
     "ember-styleguide": "^4.2.0",
-    "ember-template-lint": "^1.3.0",
+    "ember-template-lint": "^2.13.0",
     "ember-tether": "^1.0.0",
     "ember-truth-helpers": "^2.1.0",
     "eslint-plugin-ember": "^7.7.2",
```

and then running `npm install`.

After you do, you can run `npm run lint:hbs` and see all the lint errors. Fixing them is a good new contributor issue.

</details>

**Comment by BradenLawrence** [comment]
Hey @ef4, I'd like to help out with this one!

**Comment by ijlee2** [comment]
@BradenLawrence Thanks for your interest in helping out with `ember-website`. If you have questions, feel free to ask us!

**Comment by BradenLawrence** [comment]
Thanks @ijlee2! The changes are making sense for the most part, but I wanted to do a quick sanity check. The linter came back with around 400 errors, mostly for angle brackets, alt text, and `rel="noopener noreferrer"`. It's a lot of changes all spread throughout the repo, and I'm worried a 400+ line diff would be difficult to review. Would it be better to split this into smaller PRs?

**Comment by ijlee2** [comment]
@BradenLawrence Sorry, I didn't read the issue description beforehand to understand what @ef4 was asking for. Now I see it.

Let me update the description so that your pull request will involve a small but meaningful work. We can create spin-off tickets to fix lint errors.

Give me about 15 min?

**Comment by BradenLawrence** [comment]
Awesome, thank you for taking a look at this!

**Comment by ijlee2** [comment]
@BradenLawrence I updated the issue's description. In short, you are to reinstall linters for `hbs` and `js`, then suppress errors by adding exceptions to the rules. Hope this works with you!

**Comment by ijlee2** [comment]
@BradenLawrence Let me work on this issue today. I want to create follow-up issues for fixing lint errors for EmberFest tomorrow.
