### ISSUE TITLE
Fix CSS lint errors

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#671]
## Background

When I upgraded lint-related packages to their latest version in https://github.com/ember-learn/ember-website/pull/670, the app didn't meet the latest standards of [stylelint](https://stylelint.io/). To get the pull request in a mergeable state, I suppressed the lint errors.

## Problem

Let's fix the CSS lint errors. 🌟

## TODOs

- [ ] You can visit [Getting Started](https://stylelint.io/user-guide/get-started) and [Configuration](https://stylelint.io/user-guide/configure) to learn more about how you'd install `stylelint` in your own project.

- [ ] To automatically fix the lint errors, run the following command:

    ```bash
    npm run lint:style -- --fix
    ```

- [ ] Update `.stylelintrc` by removing all rules that we were able to fix in the previous step.

- [ ] The only rule that couldn't be fixed will be `no-descending-specificity`. You can either try to fix this manually, or make an exception in `.stylelintrc`. (The exception had already existed before I made the pull request.)

**Comment by ijlee2** [comment]
Hi, everyone. I created this issue for [EmberFest Contributors Workshop](http://emberfest.eu/), to be held on October 16. Please allow a workshop participant the chance to claim and work on this issue first.

If the issue is still open after October 16, anyone is welcome to sign up for the issue. Thanks, and happy Hacktoberfest! 🎃

**Comment by manurampandit** [comment]
I would like to work on this as part of EmberFest Contributors workshop

**Comment by ijlee2** [comment]
Hi, @manurampandit . Thank you for joining the workshop and helping out! Let us know if you have any questions.

**Comment by ijlee2** [comment]
Completed in #676.
