### ISSUE TITLE
Fix JS lint errors

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#672]
## Background

When I upgraded lint-related packages to their latest version in https://github.com/ember-learn/ember-website/pull/670, the app didn't meet the latest standards of [eslint](https://eslint.org/docs/rules/) and [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember). To get the pull request in a mergeable state, I suppressed the lint errors.

## Problem

Let's fix the JS lint errors. 🌟

Warning: I **highly recommend** pushing a commit after you fix 1 _type_ of lint error. Because there are very few application and rendering tests, I also recommend that you run the app locally to check if you may have introduced a bug.

## TODOs

- [ ] Remove (or comment out) 1 of the [six lint checks in `.eslintrc.js`](https://github.com/ember-learn/ember-website/blob/50773b6a94465fa5b723d0b53a3530063c65694a/.eslintrc.js#L34-L39). Run the following command to see where errors occur:

    ```bash
    npm run lint:js
    ```

- [ ] Fix errors, commit the changes, then make a push to GitHub. The CI may help with asserting that the app continues to work.

- [ ] Repeat the two steps above for the 5 remaining lint error types.

- [ ] EmberFest participants: If there are lint errors that you weren't able to fix on time, no worries. Please feel free to submit a pull request with the changes that you were able to make. 🙌🏼

## References

- [ember/no-assignment-of-untracked-properties-used-in-tracking-contexts](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.md)
- [ember/no-get](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md)
- [ember/no-get-with-default](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get-with-default.md)
- [ember/require-computed-property-dependencies](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-property-dependencies.md)
- [ember/use-ember-data-rfc-395-imports](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/use-ember-data-rfc-395-imports.md)
- [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins)
- Codemod: [ember-data-codemod](https://github.com/ember-codemods/ember-data-codemod)

**Comment by ijlee2** [comment]
Hi, everyone. I created this issue for [EmberFest Contributors Workshop](http://emberfest.eu/), to be held on October 16. Please allow a workshop participant the chance to claim and work on this issue first.

If the issue is still open after October 16, anyone is welcome to sign up for the issue. Thanks, and happy Hacktoberfest! 🎃

**Comment by Andy9822** [comment]
I'll take this one !

**Comment by ijlee2** [comment]
Hi, @Andy9822. Thanks for your interest in helping out with the Ember Website!

Yes, if you are able to fix all lint errors, then by the end, you will be able to remove [all 6 exceptions](https://github.com/ember-learn/ember-website/blob/50773b6a94465fa5b723d0b53a3530063c65694a/.eslintrc.js#L34-L39) and run `npm run lint:js` without error.

To confirm before I assign you to this issue, are you participating in the EmberFest Contributors Workshop tomorrow? I want to check that there'll be enough issues for people to work on, before asking the general public for help.

**Comment by manurampandit** [comment]
@ijlee2 - If this is not yet picked up, want to pick this up next.

**Comment by ijlee2** [comment]
@manurampandit Assigned!

**Comment by manurampandit** [comment]
Thanks, working on it.

**Comment by ijlee2** [comment]
Now that #678 has been merged, 1 lint rule remain as exception:

- `ember/require-computed-property-dependencies`

I think we can address this rule when we gradually convert components to Glimmer in subsequent issues and pull requests. As a result, we can consider this issue completed. 🙌🏼
