### ISSUE TITLE
Fix HBS lint errors

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#673]
## Background

When I upgraded lint-related packages to their latest version in https://github.com/ember-learn/ember-website/pull/670, the app didn't meet the latest standards of [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint). To get the pull request in a mergeable state, I suppressed the lint errors.

## Problem

Let's fix the HBS lint errors. 🌟

Warning: I **highly recommend** pushing a commit after you fix 1 _type_ of lint error. Because there are very few application and rendering tests, I also recommend that you run the app locally to check if you may have introduced a bug.

To avoid merge conflicts with #672, I may also recommend either (1) avoiding fixing lint errors that involve updating the backing class, or (2) coordinating the updates with the assignee for #672.

Due to the sheer number of errors, you may also create more than 1 pull request. Each pull request can target 2 or 3 types of lint errors, for example.

## TODOs

- [ ] Remove (or comment out) 1 of the [nine lint checks in `.template-lintrc.js`](https://github.com/ember-learn/ember-website/blob/50773b6a94465fa5b723d0b53a3530063c65694a/.template-lintrc.js#L12-L20). Run the following command to see where errors occur:

    ```bash
    npm run lint:hbs
    ```

- [ ] Fix errors, commit the changes, then make a push to GitHub. The CI may help with asserting that the app continues to work.

- [ ] Repeat the two steps above for the 8 remaining lint error types.

- [ ] EmberFest participants: If there are lint errors that you weren't able to fix on time, no worries. Please feel free to submit a pull request with the changes that you were able to make. 🙌🏼

## References

- [link-rel-noopener](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/link-rel-noopener.md)
- [no-action](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md)
- [no-curly-component-invocation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-curly-component-invocation.md)
- [no-html-comments](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-html-comments.md)
- [no-implicit-this](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-implicit-this.md)
- [no-obsolete-element](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-obsolete-elements.md)
- [no-positive-tabindex](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-positive-tabindex.md)
- [require-button-type](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-button-type.md)
- [require-valid-alt-text](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-valid-alt-text.md)

**Comment by ijlee2** [comment]
Hi, everyone. I created this issue for [EmberFest Contributors Workshop](http://emberfest.eu/), to be held on October 16. Please allow a workshop participant the chance to claim and work on this issue first.

If the issue is still open after October 16, anyone is welcome to sign up for the issue. Thanks, and happy Hacktoberfest! 🎃

**Comment by BradenLawrence** [comment]
Hi @ijlee2! I had done some of this while working on #669, is it alright if I push up what I've got so far?

**Comment by ijlee2** [comment]
@BradenLawrence Yes, please! Sorry again for taking over package updates on a short notice.

**Comment by ijlee2** [comment]
Now that #673 has been merged, 2 lint rules remain as exceptions:

- `no-action`
- `no-html-comments`

The second one existed prior to my upgrading `ember-template-lint` in #670. Let's work on removing the `{{action}}` helpers piecemeal by converting components to Glimmer in subsequent issues and pull requests.

As a result, we can consider this issue completed. 🙌🏼
