### ISSUE TITLE
Octanify adapters, models, and serializers

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#703]
## Background

Over the next month or so, we want to upgrade `ember-source` to the latest (`v3.24` at the time of writing) and ensure that the app follows latest practices in Ember Octane.

## Description

In #702, I added unit tests for the `application` adapter and the models that we use to load data in emberjs.com. Now that we have tests, let's rewrite the adapter and models to use native class. (Serializer too.)

## TODOs

Please make 3 commits for your pull request (one commit after completing each TODO item).

- [ ] Rewrite `application` adapter in native class.
- [ ] Rewrite models in native class. In `project` and `sponsor` models, please change computed properties to getters (caching not needed).
- [ ] Rewrite `application` serializer in native class.

## References

If you are unsure about the syntax for Ember Data in native class, please have a look at the following links in the Ember Guides:

- https://guides.emberjs.com/release/models/customizing-adapters/
- https://guides.emberjs.com/release/models/defining-models/
- https://guides.emberjs.com/release/models/customizing-serializers/

**Comment by bertdeblock** [comment]
@ijlee2 I can pick this up if that's okay?

**Comment by ijlee2** [comment]
@bertdeblock Absolutely. Thank you!
