### ISSUE TITLE
Remove unused helpers

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#705]
## Background

Over the next month or so, we want to upgrade `ember-source` to the latest (`v3.24` at the time of writing) and ensure that the app follows latest practices in Ember Octane.

## Description

There seems to be 2 helpers, `{{asset-map}}` and `{{tag-url-path}}`, that are not being used. Remove these if they are truly unused.

## TODOs

- [ ] From `git` commit history, investigate why these helpers had been created. If you can find a link to the **commit** or **pull request** that had created the helper, that'd be great!
- [ ] Try running `ember d helper asset-map` to test if the helper isn't needed.
  - Run the app locally in development environment (`ember s`). Visit different pages to ensure that the app works without error (a smoke test). Run the app in production environment (`ember s --prod`) and repeat the smoke test.
- [ ] Try running `ember d helper tag-url-path` to test if the helper isn't needed.
  - Run the app locally in development environment (`ember s`). Visit different pages to ensure that the app works without error (a smoke test). Run the app in production environment (`ember s --prod`) and repeat the smoke test.

**Comment by czikarito** [comment]
@ijlee2 I can pick this up

**Comment by ijlee2** [comment]
@czikarito Great, thank you!
