### ISSUE TITLE
Rewrite controllers in native class (Part 2 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#722]
## Background

Over the next month or so, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.

## Description

In #720, I added unit tests for controllers. These tests, in particular, assert how we transform and sort data before we pass them to a route template.

Now that we have tests, let's rewrite the controllers to use native class.

## TODOs

Please update the following controllers that have a (relatively) high risk of breaking the app. Currently, unit tests are not enough to say that the app continues to function as intended. A manual check is needed.

- [ ] Rewrite `ember-community-survey-2016` controller in native class.
- [ ] Rewrite `ember-community-survey-2017` controller in native class.
- [ ] Rewrite `ember-community-survey-2018` controller in native class.
- [ ] Rewrite `ember-community-survey-2019` controller in native class.
- [ ] Rewrite `community.meetups.index` controller in native class.
- [ ] Rewrite `mascots.index` controller in native class.

## References

If you are unsure about the syntax for controllers in native class, please have a look at the following links in the Ember Guides:

- https://guides.emberjs.com/release/routing/controllers/
- https://guides.emberjs.com/release/routing/query-params/
