### ISSUE TITLE
Rewrite routes in native class (Part 1 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#724]
## Background

Over the next month or so, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.

## Description

In #723, I added unit tests for routes. These tests, in particular, assert what data we load in the `model` hook.

Now that we have tests, let's rewrite the routes in native class.

## TODOs

Please update the following routes that have a low risk of breaking the app. We can rely on unit tests to say that the app functions as intended.

- [ ] Rewrite `ember-users` route in native class.
- [ ] Rewrite `learn` route in native class.
- [ ] Rewrite `mascots` route in native class.
- [ ] Rewrite `releases` route in native class.
- [ ] Rewrite `sponsors` route in native class.
- [ ] Rewrite `team` route in native class.
- [ ] Rewrite `community.meetups.index` route in native class.
- [ ] Rewrite `releases.beta` route in native class.
- [ ] Rewrite `releases.canary` route in native class.
- [ ] Rewrite `releases.index` route in native class.
- [ ] Rewrite `releases.lts` route in native class.
- [ ] Rewrite `releases.release` route in native class.

## References

If you are unsure about the syntax for routes in native class, please have a look at the following links in the Ember Guides:

- https://guides.emberjs.com/release/routing/specifying-a-routes-model/

**Comment by czikarito** [comment]
@ijlee2 I can pick this one

**Comment by ijlee2** [comment]
@czikarito Great, thank you!
