### ISSUE TITLE
Rewrite routes in native class (Part 2 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#725]
## Background

Over the next month or so, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.

## Description

In #723, I added unit tests for routes. These tests, in particular, assert what data we load in the `model` hook.

Now that we have tests, let's rewrite the routes in native class.

## TODOs

Please update the following routes that have a (relatively) high risk of breaking the app. Currently, unit tests are not enough to say that the app continues to function as intended. A manual check is needed.

- [ ] Rewrite `application` route in native class.
- [ ] Rewrite `ember-community-survey-2016` route in native class.
- [ ] Rewrite `ember-community-survey-2017` route in native class.
- [ ] Rewrite `ember-community-survey-2018` route in native class.
- [ ] Rewrite `ember-community-survey-2019` route in native class.
- [ ] Rewrite `statusboard` route in native class.
- [ ] Rewrite `team-redirect` route in native class.

Note, the `classNames: ['ember-community-survey']` in `ember-community-survey-*` routes adds the class `.ember-community-survey` at the application route level. In native class, you can write `classNames = ['ember-community-survey'];`.

## References

If you are unsure about the syntax for routes in native class, please have a look at the following links in the Ember Guides:

- https://guides.emberjs.com/release/routing/specifying-a-routes-model/
