### ISSUE TITLE
Octanify <EmberSurvey> component (Part 1 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#740]
## Background

Over the next month or so, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.

## Description

Parts 1 and 2, together, involve creating a component called `<CtaEmberCommunitySurvey>`. This is a Glimmer component that will eventually replace `<EmberSurvey>` (a classic component).

## Motivation

The `<EmberSurvey>` component has a few issues:

- It is a classic component and we're trying to Octanify the app.
- The component relies on knowing how to configure `config/environment.js` file. Because the survey happens only once a year, it's difficult to pass this tribal knowledge to new contributors.

    ```javascript
    // config/environment.js

    let ENV = {
      survey: {
        endDate: '2021-03-01',
        route: 'ember-community-survey-2021',
        title: '2021 Ember Community Survey',
      },
    };
    ```

- The component's backing class is unnecessarily complex because we do date calculations to show a custom message. The custom message can be seen in only 1 route (the survey page). 
- The unnecessary complexity from configuration and date calculations leaked into rendering tests for `<EmberSurvey>`.

The `<CtaEmberCommunitySurvey>` component will fix these issues because it asks for the following requirements:

- The component is rendered, if and only if, we (contributors) add the component to `app/templates/application.hbs`.

    ```handlebars
    {{!-- app/templates/application.hbs --}}

    <CtaEmberCommunitySurvey
      @surveyRoute="ember-community-survey-2021"
      @surveyTitle="2021 Ember Community Survey"
    />
    ```

- The message is always the same. We will hide the survey reminder when the user:
    - Clicks on the close button to dismiss the message
    - Clicks on the link to the survey page
    - Lands on the survey page directly

## TODOs

- [ ] Use Ember CLI to create `<CtaEmberCommunitySurvey>`.

    ```bash
    ember g component cta-ember-community-survey --gc
    ```

- [ ] Copy-paste the following starter code for the component's template and backing class.

    <details>
    <summary>app/components/cta-ember-community-survey.hbs</summary>

    ```handlebars
    {{#if this.showReminder}}
      <div
        class="survey-reminder-wrapper"
        data-test-survey-reminder
      >
        <div data-test-message>
          Take the
          <LinkTo
            data-test-link={{@surveyTitle}}
            @route={{@surveyRoute}}
          >
            {{@surveyTitle}}
          </LinkTo>
        </div>

        <button
          aria-label="Dismiss this message"
          class="toggle-close hide-on-mobile"
          data-test-button="Close"
          type="button"
          {{on "click" this.closeSurveyReminder}}
        >
          <span aria-hidden="true">x</span>
        </button>
      </div>
    {{/if}}
    ```
    </details>

    <details>
    <summary>app/components/cta-ember-community-survey.js</summary>

    ```javascript
    import { action } from '@ember/object';
    import Component from '@glimmer/component';
    import { tracked } from '@glimmer/tracking';

    export default class CtaEmberCommunitySurveyComponent extends Component {
      @tracked showReminder = true;

      @action closeSurveyReminder() {
        this.showReminder = false;
      }
    }
    ```
    </details>

- [ ] Copy-paste the following start code for the component's rendering tests. Then, complete writing the 2 rendering tests.

    <details>
    <summary>tests/integration/components/cta-ember-community-survey-test.js</summary>

    ```javascript
    import { click, render } from '@ember/test-helpers';
    import { hbs } from 'ember-cli-htmlbars';
    import { setupRenderingTest } from 'ember-qunit';
    import { module, test } from 'qunit';

    module('Integration | Component | cta-ember-community-survey', function (hooks) {
      setupRenderingTest(hooks);

      test('We can display a survey reminder', async function (assert) {
        await render(hbs`
          <CtaEmberCommunitySurvey
            @surveyRoute="ember-community-survey-2020"
            @surveyTitle="2020 Ember Community Survey"
          />
        `);

        // TODO: Assert that the survey reminder exists

        // TODO: Assert the message of the survey reminder

        // TODO: Assert the URL of the survey link
      });

      test('We can click the Close button to hide the survey reminder', async function (assert) {
        await render(hbs`
          <CtaEmberCommunitySurvey
            @surveyRoute="ember-community-survey-2020"
            @surveyTitle="2020 Ember Community Survey"
          />
        `);

        // TODO: Click the Close button

        // TODO: Assert that the survey reminder does not exist
      });
    });
    ```
    </details>

**Comment by czikarito** [comment]
@ijlee2 I can pick this

**Comment by ijlee2** [comment]
@czikarito Thanks! If you have questions, please feel free to reach out here, or on Discord in `#dev-ember-learning` channel.
