### ISSUE TITLE
Octanify <EmberSurvey> component (Part 2 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#741]
## Background

Over the next month or so, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.

## Description

Parts 1 and 2, together, involve creating a component called `<CtaEmberCommunitySurvey>`. This is a Glimmer component that will eventually replace `<EmberSurvey>` (a classic component).

## Motivation

Please see the Motivation section in [Part 1](https://github.com/ember-learn/ember-website/issues/740#issue-792884566).

## TODOs

Note, this issue is blocked by [Part 1](https://github.com/ember-learn/ember-website/issues/740).

**To help with code review, please create 1 commit for each TODO item (a total of 4 commits).**

- [ ] Update the template of `<CtaEmberCommunitySurvey>` so that, when a user clicks on the link to the survey page, we don't show the survey reminder anymore. Add a rendering test that asserts this behavior.

- [ ] Update the component so that, when a user lands on the route `@surveyRoute` directly, we don't show the survey reminder. Note, this will involve injecting the `router` service and looking at `this.router.currentRouteName`.

    You may try to add a rendering test. (It's not easy, and may not be considered a good practice, to mock the `router` service.) I think it's enough to check the behavior by running the app locally. You can temporarily add the following code, for example:

    ```handlebars
    {{!-- app/templates/application.hbs --}}

    <CtaEmberCommunitySurvey
      @surveyRoute="ember-community-survey-2020"
      @surveyTitle="2020 Ember Community Survey"
    />
    ```

- [ ] By now, the `<CtaEmberCommunitySurvey>` component should meet feature parity with `<EmberSurvey>`. Use the Ember CLI to remove the `<EmberSurvey>` component. Don't forget to remove any references to `<EmberSurvey>` component.

- [ ] Now that `<EmberSurvey>` component is gone, we can tidy the project a little. In `.eslintrc.js`, we can remove the lint exception `ember/no-actions-hash`. We can also run `yarn remove ember-inflector` to uninstall the addon.

**Comment by czikarito** [comment]
Hi @ijlee2!
quick question 
 > when a user clicks on the link to the survey page

By survey page link you mean passed `@surveyRoute` (`/ember-community-survey-2020` in the example above)?

**Comment by ijlee2** [comment]
@czikarito Yep, that's correct.

I was thinking of the case, when a user enters the URL `https://emberjs.com/ember-community-survey-2020` (assuming that we passed the argument `@surveyRoute="ember-community-survey-2020"` to the component in `app/templates/application.hbs`), we shouldn't show them the survey reminder since they are already on the survey page.
