### ISSUE TITLE
Automatically alternate background color in ember-community-survey pages

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-website#767]
## Description

Currently, we (maintainers and contributors) have to manually alternate background color in `ember-community-survey` pages. A simplified example is shown below:

```handlebars
{{!-- app/templates/ember-community-survey-2016.hbs --}}

<EmberCommunitySurvey::Section
  @hasDarkBackground={{false}}
  @sectionTitle="Developer Experience"
/>

<EmberCommunitySurvey::Section
  @hasDarkBackground={{true}}
  @sectionTitle="Ember in Enterprise: Employment Status & Size"
/>

<EmberCommunitySurvey::Section
  @hasDarkBackground={{false}}
  @sectionTitle="Ember Version"
/>

<EmberCommunitySurvey::Section
  @hasDarkBackground={{true}}
  @sectionTitle="Ember Data Version"
/>

...
```

Manually alternating the background color is prone to error and causes more lines of changed code in a pull request than necessary.

Let's use CSS's `:nth-child()` selector to automatically alternate the background color.

## TODOs

To help with reviewing your pull request, I recommend making a commit after completing a TODO. (A total of 3 commits.)

- [ ] Open the template file for `<EmberCommunitySurvey::Section>` component. Remove the argument support for `@hasDarkBackground` (used once, in the outermost `<div>` container).

    ```handlebars
    {{!-- app/components/ember-community-survey/section.hbs --}}

    {{!-- Before: Line 1 --}}
    <div class={{if @hasDarkBackground "bg-light-muted"}}>

    {{!-- After: Line 1 --}}
    <div>
    ```

    When you visit [http://localhost:4200/ember-community-survey-2020](http://localhost:4200/ember-community-survey-2020), you will see that _all_ sections now have a light gray background.

- [ ] In the template, give a unique class name to the outermost `<div>` container:

    ```handlebars
    {{!-- app/components/ember-community-survey/section.hbs --}}

    {{!-- Before: Line 1 --}}
    <div>

    {{!-- After: Line 1 --}}
    <div class="survey-section__container">
    ```

    Then, add the following code to the beginning of the stylesheet `app/styles/components/survey-section.css`:

    ```css
    .survey-section__container:nth-child(2n + 1) {
      /* Definition of .bg-light-muted */
      background-color: var(--color-gray-200);
      color: var(--color-gray-700);
    }

    .survey-section__title-container {
      ...
    ```

    When you visit [http://localhost:4200/ember-community-survey-2020](http://localhost:4200/ember-community-survey-2020), you will see that _all odd_ sections now have a dark gray background.

- [ ] Time to clean up code. Remove the argument `@hasDarkBackground` from all `<EmberCommunitySurvey::Section>`. You will want to update the following files:

    - `app/templates/ember-community-survey-2016.hbs`
    - `app/templates/ember-community-survey-2017.hbs`
    - `app/templates/ember-community-survey-2018.hbs`
    - `app/templates/ember-community-survey-2019.hbs`
    - `app/templates/ember-community-survey-2020.hbs`
    - `app/templates/ember-community-survey-2021.hbs`
    - `tests/integration/components/ember-community-survey/section-test.js`

    Note, we do not want to remove the argument `@hasDarkBackground` from `<EmberCommunitySurvey::Sponsor>`. The `<EmberCommunitySurvey::Sponsor>` component is to share the same background color as the last `<EmberCommunitySurvey::Section>` component. We can guarantee the same color if the argument `@hasDarkBackground` is present.

**Comment by herzzanu** [comment]
@ijlee2 Thanks for the detailed explanations, it just made the job so much easier. I took a stub at it here https://github.com/ember-learn/ember-website/pull/770 Can you please have a look?
