### ISSUE TITLE
General Branding Updates

### ISSUE THREAD

**Issue by wifelette** [ember-learn/ember-website#773]
Putting this here so we can all track the todos. 

**Tasks @pichfl is taking care of**:

- [x] Send @wifelette vectors of all the updated Tertiary Logo designs
- [x] Update the not-yet-released `TypedEmber` logo to match the new Tertiary design
- [x] Update the Brand page with all these new assets (#774)
- [x] Fix the weirdness with the _Naming_ section headline on the Brand page

**Tasks @jeffdaley is taking care of**:

- [x] Update the Brand Guide PDF to include the new Tertiary logos, as well as the new Glimmer and Embroider logo sections
- [x] Update the Brand page with a new section for the Glimmer and Embroider logos
- [x] Update the logo on the Glimmer repo/org once the art is ready

**Tasks @mansona can hopefully take care of**:

- [ ] The updated Tertiary logos will need to be shared with any stakeholders for the various projects so their websites, assets, etc. can be updated accordingly

**Tasks @ef4 will take care of**:

- [x] Update the logo on the [Embroider repo/org](https://github.com/embroider-build) once the art is ready

**Comment by jeffdaley** [comment]
Symbol for Embroider org:
![Embroider Symbol](https://user-images.githubusercontent.com/754957/109187583-08045700-7760-11eb-8fcd-2491f638d925.png)

**Comment by ef4** [comment]
Embroider org is now updated:
<img width="554" alt="Screen Shot 2021-03-01 at 2 26 14 PM" src="https://user-images.githubusercontent.com/319282/109548010-18873b00-7a9a-11eb-928d-afc8c05c6d11.png">

**Comment by wifelette** [comment]
@mansona @pichfl This issue is complete in terms of my, Ed and Jeff's tasks :) You can potentially separate out the two remaining items into other issues, or just take care of them, but reminder!

**Comment by pichfl** [comment]
@mansona @wifelette I forgot to ask about this, but what is broken about the headline? It does look normal to me.

**Comment by jeffdaley** [comment]
Whoops, I took care of that one, just forgot to check it off.

**Comment by mansona** [comment]
@wifelette I auto-closed this as I just completed the last item in it, I hope that's ok 😄
